### ISSUE TITLE
Not able to open opensignal file with multiple sensor data using opensignalsreader

### ISSUE THREAD

**Issue by harshal5789** [PGomes92/opensignalsreader#5]
acq = OpenSignalsReader('FCz_EEG-ACC_standing ideal.txt')
Traceback (most recent call last):

  File "<ipython-input-60-ef4d4bae5383>", line 1, in <module>
    acq = OpenSignalsReader('FCz_EEG-ACC_standing ideal.txt')

  File "C:\Users\HARSHAL\Anaconda3\lib\site-packages\opensignalsreader\opensignalsreader.py", line 92, in __init__
    self._read_file(os_file)

  File "C:\Users\HARSHAL\Anaconda3\lib\site-packages\opensignalsreader\opensignalsreader.py", line 124, in _read_file
    self._read_sensordata()

  File "C:\Users\HARSHAL\Anaconda3\lib\site-packages\opensignalsreader\opensignalsreader.py", line 208, in _read_sensordata
    self._converted_signals.update({sensor: self._convert_data(sensor, data[:, -n])})

  File "C:\Users\HARSHAL\Anaconda3\lib\site-packages\opensignalsreader\opensignalsreader.py", line 251, in _convert_data
    output = self.transfer_functions[sensor](samples, self.sampling_resolution[sensor])

  File "C:\Users\HARSHAL\Anaconda3\lib\site-packages\opensignalsreader\transfer_functions\bit.py", line 147, in eeg
    _check_ranges(eeg_samples, 'EEG')

  File "C:\Users\HARSHAL\Anaconda3\lib\site-packages\opensignalsreader\transfer_functions\bit.py", line 780, in _check_ranges
    % (sensor, np.min(signal), units[sensor], ranges[sensor][1], units[sensor]), stacklevel=2)

TypeError: must be real number, not str

If i used opensignalsreader for single sensor data file then its perfectly work, multisensor data file gives above error.

help me...

**Comment by karoanja** [comment]
Hello, I am having the same issue. Can ypu please help with that? Ty.
